#!/bin/bash

ESC=$(printf "\033");

FILES=$(
	git diff-index HEAD \
	| grep ".js$" \
	| grep "^:"   \
	| perl -pe 's/.*?\s[DAM]\s+//g' \
)

echo $FILES

ERRORS=0

for file in $FILES; do

	echo "Checking $file..."
	ERROR=$(npx babel $file 2>&1 1>/dev/null)

	if [[ $? != 0 ]]; then
		echo $ERROR | sed "s,.*,    ${ESC}[31m&${ESC}[0m,"
		ERRORS=1
	fi
done

make test

if [[ $? != 0 ]]; then
	ERRORS=1
fi

if [[ $ERRORS == 1 ]]; then
	echo "Commit aborted."
	exit 1
else
	exit 0
fi
